os:
  - linux
  - osx
sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
notifications:
  irc:
    nick: fbx
    channels:
      - irc.uriirc.org:16667#hyeon
    template:
      - "#%{build_number} %{result}, %{build_url}"
    skip_join: true
